# Generated by Django 5.2.3 on 2025-07-14 13:56

import ckeditor_uploader.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[470, 315], upload_to='news/images', verbose_name='Картинка превью')),
                ('image_top', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[1080, 450], upload_to='news/images', verbose_name='Картинка вверху статьи (1080x450)')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, help_text='Если не заполнено, создается на основе поля Назавание', max_length=255, null=True, verbose_name='ЧПУ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('content_editor', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Редактор')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('content_en', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('content_ru', models.TextField(blank=True, null=True, verbose_name='Контент')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='news/images', verbose_name='Картинка')),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.newsitem')),
            ],
        ),
    ]
