# Generated by Django 5.2.3 on 2025-06-18 18:01

import ckeditor_uploader.fields
import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True, verbose_name='Номер П/П')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[590, 330], upload_to='case/gallery')),
                ('description', models.TextField(null=True, verbose_name='Короткое описание')),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True, verbose_name='Номер П/П')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('html_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='СЕО контент')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('a', models.CharField(max_length=255, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Faq',
                'verbose_name_plural': 'Faq',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('icon', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[100, 100], upload_to='service/icon')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
            ],
            options={
                'verbose_name': 'Преимущества услуги',
                'verbose_name_plural': 'Преимущества услуги',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
            ],
            options={
                'verbose_name': 'Стоимость',
                'verbose_name_plural': 'Стоимость',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
            ],
            options={
                'verbose_name': 'Этапы услуги',
                'verbose_name_plural': 'Этапы услуги',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='CaseGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True, verbose_name='Номер П/П')),
                ('image', models.FileField(null=True, upload_to='case/gallery')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная картинка')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.case')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки кейсов',
                'ordering': ('-is_main', 'order_num'),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=1, null=True, verbose_name='Номер П/П')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображать?')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True, verbose_name='ЧПУ')),
                ('icon', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[100, 100], upload_to='service/icon')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[1920, 700], upload_to='service/icon')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Короткое описание')),
                ('about_text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='О нас')),
                ('category', models.ManyToManyField(related_name='services', to='catalog.category', verbose_name='Категория')),
                ('faqs', models.ManyToManyField(blank=True, to='catalog.faq')),
                ('features', models.ManyToManyField(blank=True, to='catalog.feature')),
                ('prices', models.ManyToManyField(blank=True, to='catalog.price')),
                ('steps', models.ManyToManyField(blank=True, to='catalog.step')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ('order_num',),
            },
        ),
        migrations.AddField(
            model_name='case',
            name='services',
            field=models.ManyToManyField(blank=True, to='catalog.service'),
        ),
        migrations.AddField(
            model_name='case',
            name='tags',
            field=models.ManyToManyField(blank=True, to='catalog.tag'),
        ),
    ]
