# Generated by Django 5.2.3 on 2025-06-18 18:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='date',
            field=models.CharField(max_length=10, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='category',
            name='html_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='СЕО контент'),
        ),
    ]
