# Generated by Django 5.2.3 on 2025-06-23 07:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_case_date_alter_category_html_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='about_text',
        ),
        migrations.AddField(
            model_name='case',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='СЕО текст'),
        ),
        migrations.AddField(
            model_name='case',
            name='html_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Редактор'),
        ),
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='СЕО Контент'),
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='service',
            name='html_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Редактор'),
        ),
        migrations.AlterField(
            model_name='category',
            name='html_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Редактор'),
        ),
    ]
