# Generated by Django 5.2.3 on 2025-06-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_service_about_text_case_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='СЕО текст'),
        ),
        migrations.AddField(
            model_name='case',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='СЕО текст'),
        ),
        migrations.AddField(
            model_name='case',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='case',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='case',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='case',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='СЕО Контент'),
        ),
        migrations.AddField(
            model_name='category',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='СЕО Контент'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='faq',
            name='a_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='a_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='faq',
            name='q_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='faq',
            name='q_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='feature',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='price',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='price',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='price',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='price',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='service',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='service',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='О нас'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='step',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='step',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='step',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='step',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
