# Generated by Django 5.2.3 on 2025-06-23 08:03

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_case_content_en_case_content_ru_case_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='content',
            new_name='about_us',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='content_en',
            new_name='about_us_en',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='content_ru',
            new_name='about_us_ru',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='image_top',
        ),
        migrations.RemoveField(
            model_name='service',
            name='html_content',
        ),
        migrations.AddField(
            model_name='service',
            name='image_middle',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[1920, 550], upload_to='service/icon'),
        ),
    ]
