# Generated by Django 5.2.3 on 2025-07-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_content_service_about_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='at_index',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='faq',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='feature',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='price',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='step',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пометка'),
        ),
        migrations.AddField(
            model_name='tag',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пометка'),
        ),
    ]
