# Generated by Django 5.2.3 on 2025-08-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_faq_at_index_faq_note_feature_note_price_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otkuda', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('kuda', models.EmailField(max_length=255, null=True, verbose_name='email')),
                ('gab', models.CharField(max_length=255, null=True, verbose_name='Телефон')),
                ('ves', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('is_done', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
