# Generated by Django 5.2.3 on 2025-08-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_callbackform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackform',
            name='gab',
            field=models.CharField(max_length=255, null=True, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='callbackform',
            name='kuda',
            field=models.CharField(max_length=255, null=True, verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='callbackform',
            name='otkuda',
            field=models.CharField(max_length=255, null=True, verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='callbackform',
            name='ves',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вус'),
        ),
    ]
