# Generated by Django 5.2.3 on 2025-08-12 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_callbackform_gab_alter_callbackform_kuda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price_calc_small_title',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок блока расчета стоимости маленький'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_calc_title',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок блока расчета стоимости большой'),
        ),
        migrations.CreateModel(
            name='PriceCalcItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Текст')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.service')),
            ],
        ),
    ]
