# Generated by Django 5.2.3 on 2025-08-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_service_price_calc_small_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecalcitem',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='pricecalcitem',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_calc_small_title_en',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок блока расчета стоимости маленький'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_calc_small_title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок блока расчета стоимости маленький'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_calc_title_en',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок блока расчета стоимости большой'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_calc_title_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок блока расчета стоимости большой'),
        ),
    ]
