# Generated by Django 5.2.3 on 2025-08-12 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_pricecalcitem_name_en_pricecalcitem_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricecalcitem',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_calc_items', to='catalog.service'),
        ),
    ]
