# Generated by Django 5.2.3 on 2025-08-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_pricecalcitem_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_index',
            field=models.FileField(blank=True, null=True, upload_to='service/icon'),
        ),
    ]
